[project]
name = "mix-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=2.2.0",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
]

[project.scripts]
mix-server = "mix_server:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
